"""Web Application Firewall (WAF) Fingerprinting Module (PB-2).

Detects active WAF defenses by inspecting response headers, cookies, block behaviors,
and probing with benign attack simulation tokens (SQLi / XSS probes).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, asdict
from typing import TYPE_CHECKING

from modules.findings import push_finding
from modules.stealth import build_client, apply_stealth_delay

if TYPE_CHECKING:
    from app.state import AppState

logger = logging.getLogger("recon_wire.waf")

# Signature database of known WAF vendors
WAF_SIGNATURES: list[dict[str, Any]] = [
    {
        "name": "Cloudflare",
        "headers": ["cf-ray", "cf-cache-status", "__cfduid", "cf-mitigated"],
        "server": ["cloudflare"],
        "body": ["attention required! | cloudflare", "ray id:", "cloudflare to restrict access"],
    },
    {
        "name": "Akamai Ghost / Kona",
        "headers": ["x-akamai-transformed", "akamai-origin-hop", "x-akamai-request-id"],
        "server": ["akamaighost", "akamaigslb"],
        "body": ["access denied", "akamaighost"],
    },
    {
        "name": "AWS WAF / CloudFront",
        "headers": ["x-amz-cf-id", "x-amzn-requestid", "x-amz-id-2"],
        "server": ["cloudfront", "awselb"],
        "body": ["request blocked by aws waf", "403 forbidden"],
    },
    {
        "name": "Imperva / Incapsula",
        "headers": ["x-cdn", "x-iinfo", "incap_ses", "visid_incap"],
        "server": ["incapsula"],
        "body": ["incapsula incident id", "powered by incapsula"],
    },
    {
        "name": "F5 BIG-IP ASM / TrafficShield",
        "headers": ["x-wa-info", "x-cnection", "bigipserver"],
        "server": ["big-ip", "bigip"],
        "body": ["the requested url was rejected. please consult with your administrator"],
    },
    {
        "name": "ModSecurity (OWASP CRS)",
        "headers": ["mod_security", "x-mod-security"],
        "server": ["mod_security"],
        "body": ["mod_security", "this error was generated by mod_security"],
    },
    {
        "name": "Sucuri CloudProxy",
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "server": ["sucuri"],
        "body": ["access denied - sucuri website firewall"],
    },
    {
        "name": "Barracuda WAF",
        "headers": ["barra_counter_session", "bnn_session"],
        "server": ["barracuda"],
        "body": ["barracuda networks"],
    },
    {
        "name": "Fastly / Signal Sciences",
        "headers": ["fastly-restarts", "x-sigsci-request-id", "x-sigsci-tags"],
        "server": ["fastly"],
        "body": ["fastly error: unknown domain"],
    },
]


@dataclass
class WAFResult:
    detected: bool
    name: str
    confidence: str     # DEFINITIVE | HIGH | SUSPECTED
    matched_vector: str # HEADER | SERVER | PROBE_BLOCK

    def to_dict(self) -> dict:
        return asdict(self)


class WAFModule:
    """Active and passive WAF fingerprinting engine."""

    def __init__(self, state: AppState) -> None:
        self.state = state

    async def run(self) -> list[WAFResult]:
        status = self.state.module_statuses.get("WAF")
        if status:
            status.state = "RUNNING"
            status.message = "Fingerprinting Web Application Firewall (WAF)..."

        cfg = self.state.config
        detected_wafs: list[WAFResult] = []

        try:
            async with build_client(cfg) as client:
                await apply_stealth_delay(cfg)

                # 1. Passive Baseline Request
                resp = await client.get(cfg.url)
                headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}
                server_val = headers_lower.get("server", "")
                body_lower = resp.text[:2000].lower()

                for sig in WAF_SIGNATURES:
                    name = sig["name"]
                    # Check headers
                    for h in sig.get("headers", []):
                        if h.lower() in headers_lower or any(h.lower() in c.lower() for c in resp.cookies.keys()):
                            detected_wafs.append(WAFResult(detected=True, name=name, confidence="DEFINITIVE", matched_vector=f"Header/Cookie: {h}"))
                            break

                    # Check server header
                    for s in sig.get("server", []):
                        if s in server_val:
                            detected_wafs.append(WAFResult(detected=True, name=name, confidence="HIGH", matched_vector=f"Server: {server_val}"))
                            break

                # 2. Active Probe Request (Non-destructive benign attack payload)
                # Send a benign generic XSS/SQL test string to check if the gateway drops or blocks it
                probe_payload = "/?id=1'+OR+'1'='1'<script>alert(1)</script>"
                probe_url = cfg.url.rstrip("/") + probe_payload
                try:
                    probe_resp = await client.get(probe_url)
                    probe_code = probe_resp.status_code
                    probe_body = probe_resp.text.lower()

                    if probe_code in (403, 406, 501, 999):
                        # Verify against body signatures
                        matched = False
                        for sig in WAF_SIGNATURES:
                            name = sig["name"]
                            for b in sig.get("body", []):
                                if b.lower() in probe_body:
                                    detected_wafs.append(WAFResult(detected=True, name=name, confidence="DEFINITIVE", matched_vector=f"Active Probe Block (HTTP {probe_code})"))
                                    matched = True
                                    break
                        if not matched and not detected_wafs:
                            detected_wafs.append(WAFResult(detected=True, name="Generic / Custom WAF", confidence="HIGH", matched_vector=f"Blocked payload with HTTP {probe_code}"))

                except Exception:
                    pass

        except Exception as exc:
            logger.error("WAF fingerprinting error: %s", exc)

        # De-duplicate results
        unique_wafs = []
        seen = set()
        for w in detected_wafs:
            if w.name not in seen:
                seen.add(w.name)
                unique_wafs.append(w)

        self.state.waf_results = unique_wafs

        # Findings
        if unique_wafs:
            for w in unique_wafs:
                await push_finding(
                    self.state.findings_queue,
                    module="WAF",
                    severity="INFO",
                    title=f"WAF Detected: {w.name} ({w.confidence})",
                    detail=f"Target protected by {w.name} Web Application Firewall. Matched via {w.matched_vector}.",
                    evidence=f"WAF signature matched on {cfg.url}",
                )
        else:
            await push_finding(
                self.state.findings_queue,
                module="WAF",
                severity="LOW",
                title="No Web Application Firewall (WAF) Detected",
                detail="Target direct web server responses show no active WAF or CDN filtering layer.",
                evidence=f"No WAF signatures observed on {cfg.url}",
            )

        if status:
            status.state = "DONE"
            status.progress = 100
            status.message = f"{unique_wafs[0].name if unique_wafs else 'No WAF'} identified"

        return unique_wafs
